services:
  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_DATABASE: accountsdb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - eazybank

  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - 3308:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_DATABASE: cardsdb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - eazybank

  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - 3309:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_DATABASE: loansdb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - eazybank

  configserver:
    image: "ashrafulsohag/configserver:s8"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --silent --fail --request GET http://localhost:8071/actuator/health/readiness | jq --exit-status '.status == \"UP\"' || exit 1"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s

    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

  eurekaserver:
    image: "ashrafulsohag/eurekaserver:s8"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --silent --fail --request GET http://localhost:8070/actuator/health/readiness | jq --exit-status '.status == \"UP\"' || exit 1"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: prod

  accounts:
    image: "ashrafulsohag/accounts:s8"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --silent --fail --request GET http://localhost:8080/actuator/health/readiness | jq --exit-status '.status == \"UP\"' || exit 1"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      # here first configserver is spring format, and second configserver is docker service name
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://accountsdb:3306/accountsdb # here port is the docker container port, not my localhost port
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  cards:
    image: "ashrafulsohag/cards:s8"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --silent --fail --request GET http://localhost:9000/actuator/health/readiness | jq --exit-status '.status == \"UP\"' || exit 1"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      # here first configserver is spring format, and second configserver is docker service name
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://cardsdb:3306/cardsdb # here port is the docker container port, not my localhost port
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  loans:
    image: "ashrafulsohag/loans:s8"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --silent --fail --request GET http://localhost:8090/actuator/health/readiness | jq --exit-status '.status == \"UP\"' || exit 1"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      # here first configserver is spring format, and second configserver is docker service name
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://loansdb:3306/loansdb # here port is the docker container port, not my localhost port
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks:
  eazybank:
    driver: bridge